name: Whatsapp Notification

on: [push, pull_request, issues, fork, watch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: kaviadigdarshan/whatsapp-actions@main
      - name: whatsapp-notify
        env:
          ACCOUNT_SID: ${{ secrets.ACCOUNT_SID }}
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          TO_WHATSAPP_NUMBER: ${{ secrets.TO_WHATSAPP_NUMBER }}
